# Fazer tupla com sinonimos de rua
street_synonyms = (
    "rua",
    "avenida",
    "alameda",
    "travessa",
    "praça",
    "largo",
    "viela",
    "estrada",
    "boulevard",
    "passagem",
    "via",
    "rodovia"
)

# Fazer tupla com nomes de cidades brasileiras
city_names = (
    "curitiba",
    "porto belo",
)

# Fazer tupla com o nome de bairros
neighborhood_names = (
    "abatia",
    "abranches",
    "agua verde",
    "ahu",
    "alto boqueirao",
    "alto da gloria",
    "alto da rua xv",
    "alto do boa vista",
    "alto da xv",
    "atuba",
    "augusta",
    "bacacheri",
    "bairros novos",
    "barreirinha",
    "batel",
    "bigorrilho",
    "boa vista",
    "bom retiro",
    "boqueirao",
    "butiatuvinha",
    "cabral",
    "cachoeira",
    "cajuru",
    "campina do siqueira",
    "campo comprido",
    "capao da imbuia",
    "capao raso",
    "cascatinha",
    "centro",
    "centro civico",
    "cic",
    "cidade industrial",
    "cristo rei",
    "fanny",
    "fazendinha",
    "ganchinho",
    "guabirotuba",
    "guaira",
    "hauer",
    "hugo lange",
    "jardim botanico",
    "jardim das americas",
    "jardim social",
    "juveve",
    "lamenha pequena",
    "lindoia",
    "merces",
    "mossungue",
    "novo mundo",
    "orleans",
    "parolin",
    "pilarzinho",
    "pinheirinho",
    "porto",
    "prado velho",
    "reboucas",
    "santa candida",
    "santa felicidade",
    "santa quiteria",
    "santo inacio",
    "sao braz",
    "sao francisco",
    "sao joao",
    "sao lourenco",
    "sao miguel",
    "sao sebastiao",
    "taboao",
    "taruma",
    "tatuquara",
    "tingui",
    "uberaba",
    "umbara",
    "vila izabel",
    "vista alegre",
    "xaxim"
)

